---
title: "2.2 Assignment"
author: "Alexa Wittlieff"
date: "July 3, 2022"
output: 
    pdf_document: default
---

```{r echo=FALSE}
setwd("C:/Users/Alexa/Documents/GitHub/Wittlieff_Alexa_DSC640_GitHubRepository/2.2 Exercises")
```

```{r include=FALSE}
library('treemapify')
library('ggplot2')
library('dplyr')
library('stringr')
library('tidyverse')
library('tidyr')
```

```{r echo = FALSE}
spend_df<- read.table('expenditures.txt',sep="\t", header=TRUE)
```

```{r echo=FALSE}
trim_df <- spend_df[spend_df$year == 2008, ]
```

```{r}
ggplot(trim_df, aes(area=expenditure, fill = category, label = paste(category, expenditure, sep = "\n"))) +
    geom_treemap() + geom_treemap_text(colour = "white", 
                                       place = "centre", 
                                       size = 15) + 
    theme(legend.position="none")+
  ggtitle("2008 Expenditures by Category")
```

```{r}
groupyr_df <- spend_df %>% group_by(year) %>% summarise(total_expenditure = sum(expenditure))
```

```{r}
ggplot(groupyr_df, aes(x=year, y=total_expenditure)) + geom_area(fill='green') +
  ggtitle("Expenditures by Year")+ theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "grey")) + xlab("Year") + ylab("Expenditure")
```

```{r}
ggplot(spend_df, aes(x=year, y=expenditure, fill=category)) + geom_area() + xlab("Year") + ylab("Expenditure") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "grey")) +
  ggtitle("Expenditures by Year and Category")
```


```{r}
ggplot(groupyr_df, aes(x=year, y=total_expenditure)) + geom_step(color="green") + xlab("Year") + ylab("Expenditure") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "grey")) +
  ggtitle("Expenditures by Year")
```