---
title: "1.2 Assignment"
author: "Alexa Wittlieff"
date: "June 19th, 2022"
output: 
    pdf_document: default
---
    
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
setwd("C:/Users/Alexa/Documents/GitHub/Wittlieff_Alexa_DSC640_GitHubRepository")
```

```{r include=FALSE}
library('ggplot2')
library('readxl')
library('purrr')
library('plyr')
library('dplyr')
library('magrittr')
library('stringr')
library('tidyverse')
library('tidyr')
```

```{r echo = FALSE}
obama_df<- read_excel('C:/Users/Alexa/Documents/GitHub/Wittlieff_Alexa_DSC640_GitHubRepository/1.2 Exercises/obama-approval-ratings.xls')
hotdog_df<-read_excel('C:/Users/Alexa/Documents/GitHub/Wittlieff_Alexa_DSC640_GitHubRepository/1.2 Exercises/hotdog-contest-winners.xlsm')
```

```{r}
# Create a bar chart
obamabc<-ggplot(data=obama_df, aes(x=Issue, y=Approve)) + geom_bar(stat="identity", color="Green", fill="Green") + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=.1)) + coord_flip() + ggtitle("Barack Obama's Approval Ratings by Issue") + xlab("Issue") + ylab("Approve")

obamabc
```

```{r}
# Convert data to long format
df_long <- gather(obama_df, Type, value, Approve:None, factor_key=TRUE)

# Build levels
df_long$Type <- factor(df_long$Type, levels = c('None', 'Disapprove', 'Approve'))    
Type <- c('Approve', 'Disapprove', 'None')

# Create stacked bar chart
obamasbc <- ggplot(df_long, aes(fill=Type, y=value, x=Issue)) + 
geom_bar(position="stack", stat="identity") + 
ggtitle("Barack Obama's Ratings: All Issues") + xlab("Issue") + ylab("Approve, Disapprove, and None") + scale_fill_manual(values = c("black","red","green")) + theme(axis.text.x = element_text(angle = 90))

# Show chart
obamasbc
```

```{r}
# Create stacked bar chart
obamasbc2 <- ggplot(df_long, aes(fill=Type, y=Issue, x=value)) + 
geom_bar(position="stack", stat="identity") + 
ggtitle("Barack Obama's Ratings: All Issues") + xlab("Approve, Disapprove, and None") + ylab("Issue") + scale_fill_manual(values = c("black","red","green"))

# Show chart
obamasbc2
```

```{r}
# Extract needed information
rating <- c(obama_df$Approve[10], obama_df$Disapprove[10], obama_df$None[10])
type <- c('Approve', 'Disapprove', 'None')

# Build data frame
data <- data.frame(group=type, value=rating)

# Plot pie chart
obamapc <- ggplot(data, aes(x="", y=rating, fill=Type))+
geom_bar(stat="identity", width=1, color="white") +
coord_polar("y", start=0) + theme_void() + 
ggtitle("Barack Obama's Ratings: Economy") + geom_text(aes(label = value), color = "white", position = position_stack(vjust = 0.5)) + scale_fill_manual(values=c("green","red","black"))

#Show chart
obamapc
```

```{r}
# Plot donut chart

# Extract needed information
rating <- c(obama_df$Approve[8], obama_df$Disapprove[8], obama_df$None[8])
type <- c('Approve', 'Disapprove', 'None')

# Build data frame
data2 <- data.frame(group=type, value=rating)

# set hole size
hsize <- 4

obamadc <- ggplot(data2, aes(x=hsize, y=rating, fill=Type))+
geom_col() +
coord_polar(theta = "y") +
xlim(c(0.2, hsize + 0.5)) +
ggtitle("Barack Obama's Ratings: Taxes")+ xlab("") + ylab("") + geom_text(aes(label = value), color = "white", position = position_stack(vjust = 0.5)) + scale_fill_manual(values=c("green","red","black"))

obamadc
```

```{r}
# Plot line chart

# Change column name
colnames(hotdog_df)[colnames(hotdog_df) == "Dogs eaten"] <- "Dogs_Eaten"

# Create a bar chart
hdline <- ggplot(hotdog_df, aes(x=Year, y= Dogs_Eaten)) + geom_line(color="red") + ggtitle("Hot Dogs Eaten by Contest Winners Each Year") + xlab("Year") + ylab("Dogs eaten")

hdline
```